services:
  crowdsec:
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: crowdsec
    environment:
      LOCAL_API_URL: http://0.0.0.0:8080
    image: crowdsecurity/crowdsec
    labels:
      homepage.description: Security Engine
      homepage.group: Security
      homepage.icon: crowdsec
      homepage.name: Crowdsec
      homepage.widget.fields: '["alerts", "bans"]'
      homepage.widget.password: ${CROWDSEC_LAPI_KEY:?crowdsec lapi key is not set}
      homepage.widget.type: crowdsec
      homepage.widget.url: http://${HOST_IP:?no host ip defined}:8080
      homepage.widget.username: localhost
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - ${DATA_PATH:?data path not defined}/crowdsec/data:/var/lib/crowdsec/data
      - ${DATA_PATH:?data path not defined}/crowdsec/config:/etc/crowdsec