networks:
  observability:
    driver: bridge
    name: observability
services:
  beszel:
    container_name: beszel
    image: henrygd/beszel
    labels:
      homepage.description: Lightweight server monitoring platform
      homepage.group: Observability
      homepage.href: https://beszel.${DOMAIN:?no domain defined}
      homepage.icon: beszel
      homepage.name: Beszel
      homepage.widget.fields: '["systems", "up"'
      homepage.widget.password: ${BESZEL_ADMIN_PASSWORD:?beszel admin password not defined}
      homepage.widget.type: beszel
      homepage.widget.url: http://beszel:8090
      homepage.widget.username: ${BESZEL_ADMIN_USER:?beszel admin user not defined}
      homepage.widget.version: 2
      traefik.enable: true
      traefik.http.routers.beszel.rule: Host(`beszel.${DOMAIN:?no domain defined}`) || Host(`systems.${DOMAIN:?no domain defined}`)
    networks:
      - observability
    ports:
      - 8090:8090
    restart: unless-stopped
    volumes:
      - /mnt/data/docker/beszel/data:/beszel_data
  beszel-agent:
    container_name: beszel-agent
    depends_on:
      - beszel
    environment:
      KEY: ${BESZEL_AGENT_KEY:?beszel agent key not defined}
      LISTEN: 45876
    image: henrygd/beszel-agent
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  grafana:
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:?grafana admin password not defined}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:?grafana admin user not defined}
      GF_USERS_ALLOW_SIGN_UP: false
    image: grafana/grafana
    labels:
      homepage.description: Metrics Visualizer
      homepage.group: Observability
      homepage.href: https://grafana.${DOMAIN:?no domain defined}
      homepage.icon: grafana
      homepage.name: Grafana
      homepage.widget.fields: '["dashboards","datasources","totalalerts","alertstriggered"]'
      homepage.widget.password: ${GRAFANA_ADMIN_PASSWORD:?grafana admin password not defined}
      homepage.widget.type: grafana
      homepage.widget.url: http://grafana:3000
      homepage.widget.username: ${GRAFANA_ADMIN_USER:?grafana admin user not defined}
      traefik.enable: true
      traefik.http.routers.grafana.rule: Host(`grafana.${DOMAIN:?no domain defined}`)
    networks:
      - observability
    ports:
      - 3333:3000
    restart: unless-stopped
    volumes:
      - /mnt/data/docker/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - /mnt/data/docker/grafana/dashboards:/var/lib/grafana/dashboards
      - /mnt/data/docker/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
  loki:
    container_name: loki
    image: grafana/loki
    networks:
      - observability
    ports:
      - 3103:3100
    restart: unless-stopped
    volumes:
      - /mnt/data/docker/loki:/loki
  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --storage.tsdb.retention.time=3650d
      - --web.enable-lifecycle
    container_name: prometheus
    environment:
      PROMETHEUS_RETENTION_TIME: 3650d
    image: prom/prometheus
    labels:
      homepage.description: Metrics collection
      homepage.group: Observability
      homepage.href: https://prometheus.${DOMAIN:?no domain defined}
      homepage.icon: prometheus
      homepage.name: Prometheus
      homepage.widget.type: prometheus
      homepage.widget.url: http://prometheus:9090
      traefik.enable: true
      traefik.http.routers.prometheus.rule: Host(`prometheus.${DOMAIN:?no domain defined}`)
    networks:
      - observability
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - /mnt/data/docker/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /mnt/data/docker/prometheus/data:/prometheus
  promtail:
    command: -config.file=/etc/promtail/config.yml
    container_name: promtail
    environment:
      PROMTAIL_CONFIG_FILE: /etc/promtail/config.yml
    image: grafana/promtail
    networks:
      - observability
    restart: unless-stopped
    volumes:
      - /mnt/data/docker/promtail/data:/var/lib/promtail/positions
      - /mnt/data/docker/promtail/promtail-config.yaml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro