networks:
  nexus:
    external: true
services:
  kromgo:
    cap_drop:
      - ALL
    container_name: kromgo
    depends_on:
      prometheus:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 16M
    environment:
      PROMETHEUS_URL: ${PROMETHEUS_URL:?PROMETHEUS_URL not set}
    healthcheck:
      test: [ "NONE" ]
    hostname: kromgo
    image: ghcr.io/kashalls/kromgo
    labels:
      homepage.description: Prometheus Badge Generator
      homepage.group: Observability
      homepage.href: https://kromgo.${DOMAIN:?DOMAIN not set}
      homepage.icon: prometheus
      homepage.name: Kromgo
      traefik.http.routers.kromgo.rule: Host(`kromgo.${DOMAIN:?DOMAIN not set}`) || Host(`stat.${DOMAIN:?DOMAIN not set}`)
    networks:
      - nexus
    ports:
      - 8082:8080
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "${PUID:?PUID not set}:${PGID:?PGID not set}"
    volumes:
      - ./data/kromgo.yaml:/kromgo/config.yaml:ro
